apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    # Success condition: the error rate should be less than or equal to 5%
    successCondition: len(result) == 0 || result[0] <= 0.05
    provider:
      prometheus:
        # This is the internal DNS address of the Prometheus instance we installed with Helm
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{job="{{args.service-name}}", status=~"5.*"}[1m])) 
          / 
          sum(rate(http_requests_total{job="{{args.service-name}}"}[1m]))