apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: checkout-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
    spec:
      containers:
      - name: checkout-api
        image: ghcr.io/stefanprodan/podinfo:6.2.2
        ports:
        - containerPort: 9898
  strategy:
    canary:
      steps:
      - setWeight: 25 # Send 25% of the traffic to the new version
      - pause: {duration: 60s} # Wait 60s for Prometheus to gather metrics
      - analysis: # Trigger the query to Prometheus
          templates:
          - templateName: success-rate
          args:
          - name: service-name
            value: checkout-api
      - setWeight: 100 # If Prometheus says OK, increase to 100%