apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkout-api
  labels:
    # kube-prometheus-stack uses this label to automatically discover ServiceMonitors
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: checkout-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s