apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # All namespace can use this secret store
metadata:
  name: global-vault
spec:
  provider:
    kubernetes:
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      remoteNamespace: vault-sim
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets